### PR TITLE
Add visual workflow to Tutorial 1: Technical Overview

### PR DESCRIPTION
**Pull request by PabRod**
## Description
This pull request appends a visualization of the full workflow (see below).

## Motivation
[Tutorial 1: Technical Overview](https://scrollprize.org/tutorial1) contains a detailed workflow description, starting from the physical object and ending with new knowledge. Every substep details inputs and outputs. When a workflow is described this nicely, it is usually worth visualizing it.

## Visualization
```mermaid
graph TD

classDef substep fill:#6fc2fc

Scanning["1. Scanning"]:::substep
Papyrus([Papyrus]) --> Scanning --> tif[/.tif image stack/]

Segmentation["2. Segmentation"]:::substep
tif --> Segmentation --> obj[/.obj 3D mesh/]

Volumes["3. Surface volumes"]:::substep
tif --> Volumes
obj --> Volumes
Volumes --> surfVol[/.tif surface volume/]

Alignment["4. Ground data truth alignment"]:::substep
Infrared[/Infrared photo/] --> Alignment --> alInf[/Aligned infrared/]
surfVol --> Alignment --> labels[/Hand-labeled binary mask/]

Ink["5. Ink detection"]:::substep
surfVol --> Ink
labels --> Ink --> predInk[/Predicted ink mask/]

Interpretation["6. Interpretation"]:::substep
predInk --> Interpretation --> Knowledge([New knowledge])
```

## Details
The visualization was made using `mermaid` and exported as `.png`. This is the mermaid source code:

```sh
graph TD

classDef substep fill:#6fc2fc

Scanning["1. Scanning"]:::substep
Papyrus([Papyrus]) --> Scanning --> tif[/.tif image stack/]

Segmentation["2. Segmentation"]:::substep
tif --> Segmentation --> obj[/.obj 3D mesh/]

Volumes["3. Surface volumes"]:::substep
tif --> Volumes
obj --> Volumes
Volumes --> surfVol[/.tif surface volume/]

Alignment["4. Ground data truth alignment"]:::substep
Infrared[/Infrared photo/] --> Alignment --> alInf[/Aligned infrared/]
surfVol --> Alignment --> labels[/Hand-labeled binary mask/]

Ink["5. Ink detection"]:::substep
surfVol --> Ink
labels --> Ink --> predInk[/Predicted ink mask/]

Interpretation["6. Interpretation"]:::substep
predInk --> Interpretation --> Knowledge([New knowledge])
```

### CODE REVIEW

**Comment by PabRod** [comment]
Dear @stephenrparsons, this pull request has been on hold for a while. I just synced it with upstream. Is there something else I can do to help?

**Comment by stephenrparsons** [comment]
@PabRod thank you for this contribution! I want to make a small tweak to the diagram but then will merge this, just haven't gotten to it quite yet

**Comment by PabRod** [comment]
No hurry. Let me know if I can provide any help. 

And greetings from the Netherlands!

**Review by stephenrparsons — APPROVED** [review]
Thank you for this contribution and for your patience while we rolled out some other website changes! I'm going to go ahead and merge this and then make a small tweak. TIL about mermaid!

**Comment by stephenrparsons** [comment]
OK feel free to let me know if you have any revisions to https://github.com/ScrollPrize/scrollprize-website/commit/8d8ce320f79b4615560ba715e53510151886d3ce!

**Pull request merged**
