### PR TITLE
Add AHRC sponsor link, use full URLs and correct formatting in Landing.js

### PR DESCRIPTION
**Pull request by danieldegroot2**
This PR changes the following
- Use full direct links
- Format actual closing brackets/lines without trailing comma
- Use the common, more recent name for "The Arts & Humanities Research Council" (not, or no longer, "of Great Britain"); and
- add its website.

Let me know if this works for you.

### CODE REVIEW

**Review by janpaul123 — CHANGES_REQUESTED** [review]
Thanks! Typically we prefer trailing commas since it reduces diffs when adding more fields. Can you back out that change?

**Comment by danieldegroot2** [comment]
@janpaul123 Sure. All of them?

**Comment by janpaul123** [comment]
Yeah I'm assuming you run some sort of linter on this? Usually you can configure them to keep trailing commas

**Comment by danieldegroot2** [comment]
Done. Also adds a trailing comma to the two entries at the end which I had split to multiple lines.

**Review by janpaul123 — APPROVED** [review]
Awesome ty!

**Pull request merged**
